[WIP] Implement image manager
TimurNurlygayanov/Project451 pull request #15
Opened 2017-03-06 15:04 UTC by Imperat

Do not merge it! Work in progress!

2017-03-06 15:09 UTC, Imperat commented on app/neural/network.py
> -from functools import reduce
this was unused import

2017-03-06 15:10 UTC, Imperat commented on app/managers/img_manager.py
> +            # Invalid file name in Archive. May be log about it?
May be we need to create some python module with application Exceptions and try in this place for example "InvalidArchivedImageName" exception?

2017-03-06 15:12 UTC, Imperat commented on app/managers/img_manager.py
> +def _read_image(file_name, digit=None):
I add option "digit" for future. If we need to implement loading images as single files, we need to call _read_image method with taken digit from user

2017-03-11 09:42 UTC, wlad031 requested changes

2017-03-11 09:42 UTC, wlad031 commented on ui/views.py
> +                          data=form.archived_images.data)
```files``` variable is unused now, i think, you may remove it
And in ```recognize``` function you need to do the same change

2017-03-11 14:59 UTC, Imperat commented on ui/views.py
> +                          data=form.archived_images.data)
Done

2017-03-11 15:03 UTC, wlad031 approved these changes

2017-03-11 15:04 UTC, merged